### PRACTICA 04: Analisis de Datos Exploratoriocon Python y Jupiter Notebook

*Proagrama de Estudios:* Ingenieria en Desarrollo y Gestion de Software

*Asignatura*: Extraccion de Conocimiento en Bases De Datos
*Docente:* M.T.I Marco A. Ramirez Hernandez
*Periodo Mayo - Agosto 2026*

*UNIDAD 2:* Preparacion de los Datos

*Nombre del estudiante:* Angel de Jesus Baños Tellez
*Matricula:* 230592
*Grado y Grupo 9°A IDGS*

---


El estudiante practicara como realizar un analisis exploratorio de datos, utilizando el lenguaje de programacion de Python y librerias comunes para la carga,manipulacion, analisis y visualizacion previa de datos (dataset)

•⁠  ⁠Pandas
•⁠  ⁠Numpy
•⁠  ⁠Seaborn
•⁠  ⁠os
•⁠  ⁠Matplotilb

1.⁠ ⁠Imporat las librerias necesarias para realizar la EDA

Comenzamos por importar la libreria que nos permita manipular los datos del dataset extraidos de una fuente de datos (datasource)

In [2]:
import pandas as pd

2. Creamos un Dataframe, leyendo ekl archivo deliitado por comas (CVS)

In [3]:
pokemons=pd.read_csv('./Pokemon.csv')

3. Imprime el resultado se la lectura

Este comanbdo imprime en una tabla las columnas y las filas den dataframe, siempre de manera estándar nos mostrará los primeros 5 y los últimos registros de dataframe.

In [10]:

pokemons

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

4. Obtenemos una muestra aleatoria de registros del dataframe usando el metodo SAMPLE.
Como parámetro de entrada podemos definir un entero que determina el tamaño de la muestra

In [5]:
pokemons.sample(7)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
689,628,Braviary,Normal,Flying,510,100,123,75,57,75,80,5,False
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
513,462,Magnezone,Electric,Steel,535,70,70,115,130,90,60,4,False
473,426,Drifblim,Ghost,Flying,498,150,80,44,90,54,80,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False

**Ejericio 1:** Realiza una muestra aleatoria de 50 pokemones

In [6]:
pokemons.sample(50)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
627,566,Archen,Rock,Flying,401,55,112,45,74,45,70,5,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
174,160,Feraligatr,Water,NaN,530,85,105,100,79,83,78,2,False
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False
341,312,Minun,Electric,NaN,405,60,40,50,75,85,95,3,False
145,134,Vaporeon,Water,NaN,525,130,65,60,110,95,65,1,False
254,235,Smeargle,Normal,NaN,250,55,20,35,20,45,75,2,False
31,26,Raichu,Electric,NaN,485,60,90,55,90,80,110,1,False
323,299,Nosepass,Rock,NaN,375,30,45,135,45,90,30,3,False
508,458,Mantyke,Water,Flying,345,45,20,50,60,120,50,4,False
749,680,Doublade,Steel,Ghost,448,59,110,150,45,49,35,6,False
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True
373,341,Corphish,Water,NaN,308,43,80,65,50,35,35,3,False
361,330,Flygon,Ground,Dragon,520,80,100,80,80,80,100,3,False
389,356,Dusclops,Ghost,NaN,455,40,70,130,60,130,25,3,False
114,106,Hitmonlee,Fighting,NaN,455,50,120,53,35,110,87,1,False
367,335,Zangoose,Normal,NaN,458,73,115,60,60,60,90,3,False
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
340,311,Plusle,Electric,NaN,405,60,50,40,85,75,95,3,False
679,618,Stunfisk,Ground,Electric,471,109,66,84,81,99,32,5,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
234,216,Teddiursa,Normal,NaN,330,60,80,50,50,50,40,2,False
475,428,Lopunny,Normal,NaN,480,65,76,84,54,96,105,4,False
45,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False
398,363,Spheal,Ice,Water,290,70,40,50,55,50,25,3,False
247,229,Houndoom,Dark,Fire,500,75,90,50,110,80,95,2,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
131,122,Mr. Mime,Psychic,Fairy,460,40,45,65,100,120,90,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
470,423,Gastrodon,Water,Ground,475,111,83,68,92,82,39,4,False
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
638,577,Solosis,Psychic,NaN,290,45,30,40,105,50,20,5,False
55,50,Diglett,Ground,NaN,265,10,55,25,35,45,95,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
449,404,Luxio,Electric,NaN,363,60,85,49,60,49,60,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
86,80,Slowbro,Water,Psychic,490,95,75,110,100,80,30,1,False
376,344,Claydol,Ground,Psychic,500,60,70,105,70,120,75,3,False
608,548,Petilil,Grass,NaN,280,45,35,50,70,50,30,5,False
291,268,Cascoon,Bug,NaN,205,50,35,55,25,25,15,3,False
662,601,Klinklang,Steel,NaN,520,60,100,115,70,85,90,5,False
443,398,Staraptor,Normal,Flying,485,85,120,70,50,60,100,4,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False
362,331,Cacnea,Grass,NaN,335,50,85,40,85,40,35,3,False
180,166,Ledian,Bug,Flying,390,55,35,50,55,110,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False

5. Obtener una muestra de rangos usando _p.iloc_

In [7]:
pokemons_100_to_200 = pokemons.iloc[100:200]
pokemons_100_to_200

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False
104,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
198,183,Marill,Water,Fairy,250,70,20,50,20,50,40,2,False
199,184,Azumarill,Water,Fairy,420,100,50,80,60,80,50,2,False

6. Como saber las columnas o atributos que tienen el datafame

In [8]:
pokemons.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

Como direccion #: El ID o número de identificaciones del Pokemon#

*Name*: El nombre del Pokemon 

*Type 1*: Se refiere a las partes elementales (tipos) asociados tanto al Pokemon como a sus movimientos

*Type 2*: Los Pokemon pueden tener hasta 2 tipos (Pokemon de tipo dual); los movimientos solo pueden tener uno.

*Total*: Representa la suma de todos los starts, lo que te da una idea de que tan "pesado" o fuerte es el Pokémon.

*HP*: (Puntos de Salud)Es que tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate(se desmaya)

*Attack* La fuerza fisica de los ataques del Pokémon.

*Defanse* Que tanto aguanta el Pokémon contra los ataques fisicos del rival.

*Sp.Atk* Ataque Especial; El poder de los movimientos especiales del Pokémon.

*Sp.Def* Defensa Especial; Que tan resistente es el pokémon ante los ataques especiales.

*Speed* Velocidad; El pokémon que tenga más velocidad ataca primero.

*Generations* Se refiere a la generacion de la serie de juegos a la que pertenece.

*Legendary*: Indica si el Pokémon es Legendario o no (son bichos muy raros y poderosos) Es un valor booleano(si/no)si

In [9]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

8. Limpieza de Datos

Dependiendo del objetivo del análisis, algunas columnas o registros no serán necesarias en nuestro dataframe, en este caso omitiremos los datos vacios, por lo que eliminaremos la columna 'Type 2' y renombraremos la columna 'Type 1' por 'Type'.

In [ ]:
jeje

**Ejercicio 02:** Consulta la METADATA de la actualización y compara los cambios con la anterior.

¿Qué cambios ves? Redacta tu respuesta

9. Visualización de los primeros datos usando el método **.head**

In [11]:
pokemons.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

**Ejercicio 03:** Muestra los últimos 10 registros del dataframe

10. Estadística básica del Dataframe.

Pandas permite emitir un reporte de estadística básica (medidas de tendencia) sobre datos cuantitativos usando el comando **.describe**

In [12]:
pokemons.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

11. Calcular el total de datos no duplicados (únicos)

Usaremos **.lean()** como función para calcular la longitud del dataframe y **.unique()** para excluir los duplicados.

**NOTA:** No considerar ID como un atributo de llave primaria, sino el total de columnas como un solo elemento u objeto.

Obteniendo los valores únicos por columna en este caso en la coluna "Name"

In [13]:
len(pokemons.Name.unique())

800

Obteniendo el total de objetos (conjunto de atributos, estrictamente iguales) unicos.

In [14]:
total_unicos = len(pokemons.drop_duplicates())
total_unicos

800

**Ejercicio 04:** Obtener el total de IDs únicos en el dataset

In [16]:
pokemons['#'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
       326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
       339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
       352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,
       365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377,
       378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390,
       391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403,
       404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416,
       417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429,
       430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442,
       443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455,
       456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468,
       469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481,
       482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494,
       495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507,
       508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520,
       521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533,
       534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546,
       547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559,
       560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572,
       573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585,
       586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598,
       599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611,
       612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624,
       625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637,
       638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650,
       651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663,
       664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676,
       677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689,
       690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702,
       703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715,
       716, 717, 718, 719, 720, 721])

**Ejercicio 05:** Obtener el total de Tipos Únicos de Pokemones

pandas nos permite agrupar los datos y contabilizar los totales usanndo **.value_counts()**

¿Cuántos Pókemones hay por Generación?

In [15]:
pokemons['Generation'].value_counts()

Generation
1    166
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64